from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("seasonstats/", views.seasonstats, name="seasonstats"),
    path("profile/", views.profile, name="profile"),
    path("retiredprofile/", views.retired_profile, name="retired_profile"),
    path("playersearch/", views.playersearch, name="playersearch"),
    path("teams/", views.teams, name="teams"),
    path("teams/ARI/", views.teamARI, name="teamARI"),
    path("teams/ATL/", views.teamATL, name="teamATL"),
    path("teams/BAL/", views.teamBAL, name="teamBAL"),
    path("teams/BUF/", views.teamBUF, name="teamBUF"),
    path("teams/CAR/", views.teamCAR, name="teamCAR"),
    path("teams/CHI/", views.teamCHI, name="teamCHI"),
    path("teams/CIN/", views.teamCIN, name="teamCIN"),
    path("teams/CLE/", views.teamCLE, name="teamCLE"),
    path("teams/DAL/", views.teamDAL, name="teamDAL"),
    path("teams/DEN/", views.teamDEN, name="teamDEN"),
    path("teams/DET/", views.teamDET, name="teamDET"),
    path("teams/GB/", views.teamGB, name="teamGB"),
    path("teams/HOU/", views.teamHOU, name="teamHOU"),
    path("teams/IND/", views.teamIND, name="teamIND"),
    path("teams/JAX/", views.teamJAX, name="teamJAX"),
    path("teams/KC/", views.teamKC, name="teamKC"),
    path("teams/LA/", views.teamLA, name="teamLA"),
    path("teams/LAC/", views.teamLAC, name="teamLAC"),
    path("teams/MIA/", views.teamMIA, name="teamMIA"),
    path("teams/MIN/", views.teamMIN, name="teamMIN"),
    path("teams/NE/", views.teamNE, name="teamNE"),
    path("teams/NO/", views.teamNO, name="teamNO"),
    path("teams/NYG/", views.teamNYG, name="teamNYG"),
    path("teams/NYJ/", views.teamNYJ, name="teamNYJ"),
    path("teams/OAK/", views.teamOAK, name="teamOAK"),
    path("teams/PHI/", views.teamPHI, name="teamPHI"),
    path("teams/PIT/", views.teamPIT, name="teamPIT"),
    path("teams/SEA/", views.teamSEA, name="teamSEA"),
    path("teams/SF/", views.teamSF, name="teamSF"),
    path("teams/TB/", views.teamTB, name="teamTB"),
    path("teams/TEN/", views.teamTEN, name="teamTEN"),
    path("teams/WAS/", views.teamWAS, name="teamWAS"),
    path("HOF/", views.HallOfFame, name="HallOfFame"),
]
