# Generated by Django 2.1.5 on 2019-06-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='Tester',
        ),
    ]
