# Generated by Django 2.1.5 on 2019-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190618_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('age', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=50)),
                ('player_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
