# Generated by Django 2.1.5 on 2019-06-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profilepics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepics',
            name='id',
        ),
        migrations.AlterField(
            model_name='profilepics',
            name='urls',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
