# Generated by Django 2.1.5 on 2019-06-19 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190618_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('games', models.CharField(max_length=50)),
                ('total_tkl', models.CharField(max_length=50)),
                ('solo_tkl', models.CharField(max_length=50)),
                ('assisted_tkl', models.CharField(max_length=50)),
                ('sck', models.CharField(max_length=50)),
                ('safties', models.CharField(max_length=50)),
                ('pass_def', models.CharField(max_length=50)),
                ('int', models.CharField(max_length=50)),
                ('int_td', models.CharField(max_length=50)),
                ('int_yards', models.CharField(max_length=50)),
                ('yards_int', models.CharField(max_length=50)),
                ('lng_int_return', models.CharField(max_length=50)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('games', models.CharField(max_length=50)),
                ('att', models.CharField(max_length=50)),
                ('comp', models.CharField(max_length=50)),
                ('comp_pct', models.CharField(max_length=50)),
                ('att_g', models.CharField(max_length=50)),
                ('yards', models.CharField(max_length=50)),
                ('yards_att', models.CharField(max_length=50)),
                ('yards_g', models.CharField(max_length=50)),
                ('td', models.CharField(max_length=50)),
                ('int', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('comp_twenty_plus', models.CharField(max_length=50)),
                ('comp_forty_plus', models.CharField(max_length=50)),
                ('sck', models.CharField(max_length=50)),
                ('sck_yards', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('games', models.CharField(max_length=50)),
                ('rec', models.CharField(max_length=50)),
                ('yards', models.CharField(max_length=50)),
                ('yards_rec', models.CharField(max_length=50)),
                ('yards_g', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('td', models.CharField(max_length=50)),
                ('rec_twenty_plus', models.CharField(max_length=50)),
                ('rec_forty_plus', models.CharField(max_length=50)),
                ('fd', models.CharField(max_length=50)),
                ('fum', models.CharField(max_length=50)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Rushing',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('games', models.CharField(max_length=50)),
                ('att', models.CharField(max_length=50)),
                ('att_g', models.CharField(max_length=50)),
                ('yards', models.CharField(max_length=50)),
                ('yards_g', models.CharField(max_length=50)),
                ('yards_c', models.CharField(max_length=50)),
                ('td', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('fd', models.CharField(max_length=50)),
                ('rush_twenty_plus', models.CharField(max_length=50)),
                ('rush_forty_plus', models.CharField(max_length=50)),
                ('fum', models.CharField(max_length=50)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profiles')),
            ],
        ),
    ]
