# Generated by Django 2.1.5 on 2019-06-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190619_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defense',
            name='id',
        ),
        migrations.RemoveField(
            model_name='passing',
            name='id',
        ),
        migrations.RemoveField(
            model_name='receiving',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rushing',
            name='id',
        ),
        migrations.AlterField(
            model_name='defense',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passing',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rushing',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
