# Generated by Django 2.1.5 on 2019-06-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190619_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defense',
            old_name='int',
            new_name='ints',
        ),
        migrations.RenameField(
            model_name='passing',
            old_name='int',
            new_name='ints',
        ),
    ]
