# Generated by Django 2.1.5 on 2019-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190619_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='passing',
            name='team_short',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
