# Generated by Django 2.1.5 on 2019-06-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_passing_team_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passing',
            name='att',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='att_g',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='comp',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='comp_forty_plus',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='comp_pct',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='comp_twenty_plus',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='games',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='ints',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='lng',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='passing',
            name='position',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='rating',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='sck',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='sck_yards',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='td',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='team',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='passing',
            name='yards',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='yards_att',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='yards_g',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='passing',
            name='year',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
