# Generated by Django 2.1.5 on 2019-06-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190620_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passing',
            name='player_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profiles'),
        ),
    ]
