# Generated by Django 2.1.5 on 2019-06-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190620_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passing',
            name='team_short',
        ),
    ]
