# Generated by Django 2.1.5 on 2019-06-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190621_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passings',
            new_name='Passing',
        ),
    ]
