# Generated by Django 2.1.5 on 2019-06-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190621_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rushings',
            new_name='Rushing',
        ),
    ]
