# Generated by Django 2.1.5 on 2019-06-21 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190621_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Defenses',
            new_name='Defense',
        ),
        migrations.RenameModel(
            old_name='Receivings',
            new_name='Receiving',
        ),
    ]
