# Generated by Django 2.1.5 on 2019-06-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190621_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('games', models.CharField(max_length=50)),
                ('total_tkl', models.CharField(max_length=50)),
                ('solo_tkl', models.CharField(max_length=50)),
                ('assisted_tkl', models.CharField(max_length=50)),
                ('sck', models.CharField(max_length=50)),
                ('safties', models.CharField(max_length=50)),
                ('pass_def', models.CharField(max_length=50)),
                ('ints', models.CharField(max_length=50)),
                ('int_td', models.CharField(max_length=50)),
                ('int_yards', models.CharField(max_length=50)),
                ('yards_int', models.CharField(max_length=50)),
                ('lng_int_return', models.CharField(max_length=50)),
                ('team_short', models.CharField(max_length=50)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='defenses',
            name='player_id',
        ),
        migrations.DeleteModel(
            name='Defenses',
        ),
    ]
