# Generated by Django 2.1.5 on 2019-06-29 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_fg_kr_p_pr'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('games', models.CharField(max_length=50)),
                ('kb', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('fg', models.CharField(max_length=50)),
                ('fg_att', models.CharField(max_length=50)),
                ('fg_perc', models.CharField(max_length=50)),
                ('fg_twenty', models.CharField(max_length=50)),
                ('fg_twenty_att', models.CharField(max_length=50)),
                ('fg_twenty_perc', models.CharField(max_length=50)),
                ('fg_thirty', models.CharField(max_length=50)),
                ('fg_thirty_att', models.CharField(max_length=50)),
                ('fg_thirty_perc', models.CharField(max_length=50)),
                ('fg_forty', models.CharField(max_length=50)),
                ('fg_forty_att', models.CharField(max_length=50)),
                ('fg_forty_perc', models.CharField(max_length=50)),
                ('fg_fifty', models.CharField(max_length=50)),
                ('fg_fifty_att', models.CharField(max_length=50)),
                ('fg_fifty_perc', models.CharField(max_length=50)),
                ('ex', models.CharField(max_length=50)),
                ('ex_att', models.CharField(max_length=50)),
                ('ex_perc', models.CharField(max_length=50)),
                ('ex_b', models.CharField(max_length=50)),
                ('team_short', models.CharField(max_length=50)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='KickReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('games', models.CharField(max_length=50)),
                ('kr', models.CharField(max_length=50)),
                ('kr_yards', models.CharField(max_length=50)),
                ('yards_kr', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('td', models.CharField(max_length=50)),
                ('kr_twenty_plus', models.CharField(max_length=50)),
                ('kr_forty_plus', models.CharField(max_length=50)),
                ('fc', models.CharField(max_length=50)),
                ('fum', models.CharField(max_length=50)),
                ('team_short', models.CharField(max_length=50)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Punting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('games', models.CharField(max_length=50)),
                ('punts', models.CharField(max_length=50)),
                ('p_yards', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('p_avg', models.CharField(max_length=50)),
                ('pb', models.CharField(max_length=50)),
                ('obp', models.CharField(max_length=50)),
                ('dp', models.CharField(max_length=50)),
                ('p_twenty', models.CharField(max_length=50)),
                ('tb', models.CharField(max_length=50)),
                ('fc', models.CharField(max_length=50)),
                ('p_ret', models.CharField(max_length=50)),
                ('p_ret_yards', models.CharField(max_length=50)),
                ('p_ret_td', models.CharField(max_length=50)),
                ('team_short', models.CharField(max_length=50)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profiles')),
            ],
        ),
        migrations.CreateModel(
            name='PuntReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('games', models.CharField(max_length=50)),
                ('pr', models.CharField(max_length=50)),
                ('pr_yards', models.CharField(max_length=50)),
                ('yards_pr', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('td', models.CharField(max_length=50)),
                ('pr_twenty_plus', models.CharField(max_length=50)),
                ('pr_forty_plus', models.CharField(max_length=50)),
                ('fc', models.CharField(max_length=50)),
                ('fum', models.CharField(max_length=50)),
                ('team_short', models.CharField(max_length=50)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='fg',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='kr',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='p',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='pr',
            name='player_id',
        ),
        migrations.DeleteModel(
            name='FG',
        ),
        migrations.DeleteModel(
            name='KR',
        ),
        migrations.DeleteModel(
            name='P',
        ),
        migrations.DeleteModel(
            name='PR',
        ),
    ]
