# Generated by Django 2.1.5 on 2019-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_hof_retireddefense_retiredfieldgoals_retiredkickreturns_retiredpassing_retiredprofiles_retiredpuntin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hof',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retireddefense',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retiredfieldgoals',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retiredkickreturns',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retiredpassing',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retiredpunting',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retiredpuntreturns',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retiredreceiving',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retiredrushing',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
    ]
