# Generated by Django 2.1.5 on 2019-07-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190725_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiredOL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('games_p', models.CharField(max_length=50)),
                ('games_s', models.CharField(max_length=50)),
                ('team_short', models.CharField(max_length=50)),
            ],
        ),
    ]
