# Generated by Django 2.1.5 on 2019-08-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_retiredol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepics',
            name='player_id',
            field=models.CharField(max_length=200),
        ),
    ]
