# Generated by Django 2.1.5 on 2019-08-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190804_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retiredpassing',
            name='team_short',
        ),
    ]
