# Generated by Django 2.1.5 on 2019-08-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_retiredpassing_team_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retireddefense',
            name='team_short',
        ),
        migrations.RemoveField(
            model_name='retiredfieldgoals',
            name='team_short',
        ),
        migrations.RemoveField(
            model_name='retiredkickreturns',
            name='team_short',
        ),
        migrations.RemoveField(
            model_name='retiredol',
            name='team_short',
        ),
        migrations.RemoveField(
            model_name='retiredpunting',
            name='team_short',
        ),
        migrations.RemoveField(
            model_name='retiredpuntreturns',
            name='team_short',
        ),
        migrations.RemoveField(
            model_name='retiredreceiving',
            name='team_short',
        ),
        migrations.RemoveField(
            model_name='retiredrushing',
            name='team_short',
        ),
    ]
